AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/NonLocalExitFromIterator:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'
